vich_uploader:
    db_driver: orm

    mappings:
        raspPic:
            uri_prefix: /images/raspPics
            upload_destination: '%kernel.project_dir%/public/images/raspPics'
            namer:
                service: Vich\UploaderBundle\Naming\HashNamer
                options: { algorithm: 'sha256', length: 50 }
            delete_on_remove: true
